name: Publish New NodeJS Package Version
run-name: Publish New NodeJS Package Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-package-to-github:
    uses: archetype-themes/workflows/publish-new-nodejs-package-version.yml